name: Rename boilerplate

on: push

jobs:
  rename-boilerplate:
    if: ${{ github.repository != 'f2acode/dynamic-github-template' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Install cookiecutter
        run: pip3 install cookiecutter

      - name: Rebuild boilerplate using cookiecutter
        run: |
          export REPO_NAME=${{ github.event.repository.name }}

          # Run cookiecutter
          cookiecutter . --no-input project_name=$REPO_NAME

          # Delete this workflow
          rm -rf .github

          # Move generated content to root directory of repo
          mv {{$REPO_NAME}}/* .
          mv {{$REPO_NAME}}/.github .

          # Remove the empty boilerplate directory
          rmdir {{$REPO_NAME}}
          rm -rf "{{[% cookiecutter.project_name %]}}"
          rm cookiecutter.json

      - name: Force push new repo contents
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: rename boilerplate'
          push_options: --force
